# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_phone',
            field=models.CharField(default='', max_length=255, verbose_name='用户手机号'),
        ),
    ]
