# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='good_content',
            field=models.CharField(default='', max_length=255, verbose_name='商品内容'),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_img',
            field=models.ImageField(default='', upload_to='goods/%Y/%m', verbose_name='用户头像'),
        ),
    ]
