# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190323_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='border',
            name='good_num',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='good_num',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_color',
            field=models.CharField(choices=[(1, '黑'), (2, '白'), (3, '灰')], default=1, max_length=255, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_parameter',
            field=models.CharField(default='', max_length=255, verbose_name='商品参数'),
        ),
    ]
