# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190324_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='good_type',
            field=models.CharField(default='', max_length=255, verbose_name='商品类型'),
        ),
    ]
